const ISSUE_STATUS_FLOW = {
  TODO: ["IN-PROGRESS", "BLOCKED"],
  "IN-PROGRESS": ["REVIEW", "BLOCKED"],
  REVIEW: ["IN-PROGRESS", "COMPLETED"],
  BLOCKED: ["IN-PROGRESS"],
  COMPLETED: [],
};

export default ISSUE_STATUS_FLOW;

console.log(ISSUE_STATUS_FLOW["TODO"]);
